/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/8.9/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "0.8.0"
}

rootProject.name = "faculty_day"
include("lesson1")
include("lesson2")
//include("lesson3")
//include("lesson4")
//include("lesson5")
//include("lesson6")
include("lesson7")
//include("simple")
include("lesson8")
include("lesson9(Homework№1)")
include("lesson10(Homework№2)")
include("lesson11(Homework№3)")
include("networks(Homework№5)")
include("spring_homework1(Homework№4)")
include("spring-rest(Homework№6)")
include("spring-rest-seminar")